### ISSUE TITLE
Debugging with maven

### ISSUE THREAD

**Issue by mgmax** [t-oster/LibLaserCut#126]
How can I debug LibLaserCut (breakpoint, single-step, etc.) within VisiCut in Netbeans? Since switching to maven it doesn't seem to work anymore. Or am I doing something wrong?

**Comment by t-oster** [comment]
If you have both projects open netbeans should recognize that and allow debugging.... I will check tomorrow

**Comment by mgmax** [comment]
After cleaning and closing everything, now it works again. Possible reasons include:
- problem is between keyboard and chair
- it depends on the order in which you open projects
- NetBeans is confused if you open the directory via a symlink
Now it works.

**Comment by t-oster** [comment]
Yes, I also checked it and it worked. I opened VisiCut and then LibLaserCut which is checked out in the same module.However the connection should work no matter where the projects are located, since NetBeans just detects that VisiCut depends on LibLaserCut with a specific version which is also an open project. Maybe you had an old "nbproject" folder in the project? With maven we do not need any netbeans specific project configuration anymore, so your folder should not need any extra files.
