### ISSUE TITLE
Ruida driver speed conversion wrong?

### ISSUE THREAD

**Issue by mgmax** [t-oster/LibLaserCut#190]
The ruida driver converts speeds  0-100%  to 0-1000mm/s. This value is hardcoded, even though the driver has settings for "Max vector cutting speed (mm/s)" and "Max vector move speed (mm/s)". These settings currently have no effect.

Do all Ruida machines have a limit of 100% = 1000 mm/s? 

If yes, these settings should probably be removed.
To do so, remove everything related to `MaxVector...` and `MAX_VECTOR_...` except for the one line where the class attribute is declared. To avoid that importing old settings fails, do not remove the attribute but mark it as `@Deprecated transient` , as in
https://github.com/t-oster/LibLaserCut/blob/bc3f41385535869d6c47f158ddb7fdb48a2997dd/src/main/java/de/thomas_oster/liblasercut/drivers/LaserToolsTechnicsCutter.java#L238-L244

If no, then the conversion should depend on the configured speed. `speed_mmps = speed_percent * max_speed / 100`

_Originally posted by @mgmax in https://github.com/t-oster/LibLaserCut/issues/186#issuecomment-1605588288_

**Comment by fblaese** [comment]
The speed hardware limit is configurable via RDWorks. Instead of removing this setting, it should be utilized for the speed conversion.
I will send a Pull Request for this (and a few other improvements) soon.

On a side note: I think that setting the speed as a percentage of the machine limits is quite counterintuitive. I would prefer an absolute speed setting in mm/s, which is automatically confined to the machine limits.
